require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  NewCops: enable

Layout/LineLength:
  Enabled: true
  Max: 150
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'spec/**/*.rb'
Rails/RakeEnvironment:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
RSpec/ExampleLength:
  Max: 15
Style/Documentation:
  Enabled: false
